version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app2/zip
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/permission.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
